"""
Event site seed data — 15 conceptual design direction profiles.
These are aesthetic/identity archetypes, not physical venues.
Review this file before running the seed loader.
"""
from datetime import datetime, timezone

EVENT_SITES: list[dict] = [
    {
        "slug": "grand-mehfil",
        "name": "Grand Mehfil",
        "site_type": "regal",
        "short_description": "Mughal grandeur meets North Indian festivity. Warm, opulent, and unapologetically grand.",
        "profile_json": {
            "styleTags": ["Mughal", "regal", "opulent", "layered", "maximalist"],
            "personaSignals": ["large family", "traditional roots", "status-aware", "celebration-first"],
            "vibeTags": ["grand", "festive", "warm", "dramatic"],
            "culturalSignals": ["North Indian", "Punjabi", "Mughal influence", "multi-day events"],
            "seasonTags": ["winter", "late autumn"],
            "settingTags": ["indoor", "palace", "banquet hall", "fort"],
            "audienceFit": ["big & festive vibe", "family-led couples", "traditional households"],
            "luxuryLevel": "high",
            "colorSignals": ["gold", "deep red", "ivory", "emerald"],
            "spatialMood": ["layered", "warm-lit", "floral-heavy", "draped ceilings"],
            "narrativeSignals": ["legacy", "abundance", "celebration", "community"],
            "plannerInterpretation": "The warmest airline in your reference: the grand scale with warmth despite it all — call for treatments where people feel a celebration that feels grand and alive, but intimately theirs."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "jewel-and-bloom",
        "name": "Jewel & Bloom",
        "site_type": "intimate",
        "short_description": "Rich jewel tones, lush florals, and deeply intimate gatherings. Elegant without being cold.",
        "profile_json": {
            "styleTags": ["intimate", "floral", "jewel-toned", "luxe-minimal", "curated"],
            "personaSignals": ["detail-oriented couple", "design-aware", "close circle", "quality over scale"],
            "vibeTags": ["warm", "intimate", "romantic", "personal"],
            "culturalSignals": ["pan-Indian", "contemporary", "cosmopolitan"],
            "seasonTags": ["winter", "spring"],
            "settingTags": ["boutique venue", "garden", "rooftop", "heritage haveli"],
            "audienceFit": ["intimate vibe", "design-conscious couples", "small guest list"],
            "luxuryLevel": "medium-high",
            "colorSignals": ["burgundy", "blush", "dusty rose", "forest green", "gold"],
            "spatialMood": ["lush", "candlelit", "flower-immersive", "cozy"],
            "narrativeSignals": ["closeness", "depth", "romance", "handcrafted moments"],
            "plannerInterpretation": "Constructed with rich emeralds and burgundy palettes with burgundy red, and a gem-embellished romance with lust florals, it is rich, moody, and deeply intimate visual direction."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "delhi-rooftop",
        "name": "Delhi Rooftop",
        "site_type": "urban",
        "short_description": "City skyline wedding with clean lines, warm tones, and modern Indian elegance.",
        "profile_json": {
            "styleTags": ["urban", "modern", "rooftop", "clean", "contemporary Indian"],
            "personaSignals": ["city professionals", "young couple", "design-led", "social media aware"],
            "vibeTags": ["sleek", "modern", "relaxed-elegant", "social"],
            "culturalSignals": ["metro India", "Delhi NCR", "cosmopolitan"],
            "seasonTags": ["winter", "late autumn"],
            "settingTags": ["rooftop", "open air", "city venue", "terrace"],
            "audienceFit": ["modern & sleek vibe", "urban couples", "young professional crowd"],
            "luxuryLevel": "medium",
            "colorSignals": ["rust", "terracotta", "cream", "warm white", "copper"],
            "spatialMood": ["open", "airy", "city-lit", "string-light accents"],
            "narrativeSignals": ["modern love", "city life", "together with friends"],
            "plannerInterpretation": "Modern Delhi celebration with dusty rose tones, clean lines, and gold accents. Perfect for a March evening breeze."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "udaipur-lakeside",
        "name": "Udaipur Lakeside",
        "site_type": "destination",
        "short_description": "Royal Rajasthan meets serene water. Heritage grandeur with a dreamy, timeless quality.",
        "profile_json": {
            "styleTags": ["royal", "heritage", "destination", "Rajput", "palace"],
            "personaSignals": ["destination wedding couple", "romance-seekers", "heritage lovers", "prestige-aware"],
            "vibeTags": ["royal", "dreamy", "timeless", "grand"],
            "culturalSignals": ["Rajasthani", "North Indian", "heritage India", "destination"],
            "seasonTags": ["winter", "early spring"],
            "settingTags": ["lake palace", "heritage hotel", "waterfront", "fort"],
            "audienceFit": ["royal & grand vibe", "destination couples", "heritage seekers"],
            "luxuryLevel": "very high",
            "colorSignals": ["marigold", "saffron", "ivory", "deep blue", "silver"],
            "spatialMood": ["palatial", "water-reflected", "majestic", "traditional"],
            "narrativeSignals": ["royalty", "legacy", "timeless romance", "Rajput heritage"],
            "plannerInterpretation": "The most naturally cinematic setting in India — a palace on water. The grandeur is built-in; direction work focuses on restraint within abundance."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "coastal-light",
        "name": "Coastal Light",
        "site_type": "beach",
        "short_description": "Breezy beach wedding. Light fabrics, ocean air, minimal decor, and natural light.",
        "profile_json": {
            "styleTags": ["beach", "coastal", "minimal", "breezy", "natural"],
            "personaSignals": ["outdoorsy couple", "travel lovers", "relaxed attitude", "non-traditional"],
            "vibeTags": ["relaxed", "natural", "breezy", "intimate"],
            "culturalSignals": ["coastal India", "Goa", "Kerala backwaters", "destination"],
            "seasonTags": ["winter", "dry season"],
            "settingTags": ["beach", "seaside", "resort", "coastal villa"],
            "audienceFit": ["relaxed & easy vibe", "beach lovers", "destination couples"],
            "luxuryLevel": "medium",
            "colorSignals": ["white", "sand", "aqua", "coral", "driftwood"],
            "spatialMood": ["open", "sun-drenched", "airy", "horizon-focused"],
            "narrativeSignals": ["freedom", "joy", "natural beauty", "escape"],
            "plannerInterpretation": "The light does most of the work. Direction focuses on fabric, movement, and the horizon — not decoration."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "jungle-soiree",
        "name": "Jungle Soirée",
        "site_type": "bohemian",
        "short_description": "Forest-set celebration with earthy textures, lanterns, and bohemian warmth.",
        "profile_json": {
            "styleTags": ["bohemian", "forest", "earthy", "organic", "textured"],
            "personaSignals": ["nature lovers", "artists", "free spirits", "unconventional thinkers"],
            "vibeTags": ["whimsical", "earthy", "warm", "adventurous"],
            "culturalSignals": ["pan-Indian", "eco-conscious", "resort destinations"],
            "seasonTags": ["winter", "early spring"],
            "settingTags": ["forest", "jungle resort", "outdoor clearing", "treehouse"],
            "audienceFit": ["whimsical & playful vibe", "outdoor adventurers", "bohemian couples"],
            "luxuryLevel": "medium",
            "colorSignals": ["terracotta", "rust", "moss green", "amber", "wood tones"],
            "spatialMood": ["canopy-lit", "lantern-hung", "organic", "layered with nature"],
            "narrativeSignals": ["adventure", "connection with nature", "freedom", "warmth"],
            "plannerInterpretation": "Earthy and warm with the forest as the primary décor element. Less is more — nature does the heavy lifting."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "old-haveli",
        "name": "Old Haveli",
        "site_type": "heritage",
        "short_description": "Intimate heritage haveli. Antique textures, courtyard settings, and old-world charm.",
        "profile_json": {
            "styleTags": ["heritage", "haveli", "antique", "intimate", "courtyard"],
            "personaSignals": ["culturally rooted couple", "heritage lovers", "intimate circle", "quality-first"],
            "vibeTags": ["intimate", "traditional", "warm", "storied"],
            "culturalSignals": ["North Indian", "Rajasthani", "old Delhi", "Shekhawati"],
            "seasonTags": ["winter", "late autumn"],
            "settingTags": ["haveli", "courtyard", "heritage house", "old quarter"],
            "audienceFit": ["traditional & rooted vibe", "heritage-conscious", "intimate gatherings"],
            "luxuryLevel": "medium",
            "colorSignals": ["ochre", "dusty rose", "turquoise", "brick red", "aged gold"],
            "spatialMood": ["enclosed courtyard", "arched passages", "oil-lamp lit", "layered textiles"],
            "narrativeSignals": ["heritage", "roots", "warmth", "memory"],
            "plannerInterpretation": "The architecture is the direction. Design work focuses on complementing old walls rather than competing with them."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "modern-minimalist",
        "name": "Modern Minimalist",
        "site_type": "minimal",
        "short_description": "Clean lines, monochrome palette, architectural spaces. Confidence through restraint.",
        "profile_json": {
            "styleTags": ["minimal", "modern", "monochrome", "architectural", "editorial"],
            "personaSignals": ["design professionals", "urban sophisticates", "curators", "less-is-more believers"],
            "vibeTags": ["modern", "sleek", "quiet luxury", "confident"],
            "culturalSignals": ["metro India", "Mumbai", "Bangalore", "contemporary"],
            "seasonTags": ["any season"],
            "settingTags": ["art gallery", "modern hotel", "industrial loft", "convention center"],
            "audienceFit": ["modern & sleek vibe", "minimalist couples", "design-led weddings"],
            "luxuryLevel": "medium-high",
            "colorSignals": ["white", "off-white", "charcoal", "warm grey", "matte black"],
            "spatialMood": ["negative space", "structured", "lit with intent", "very clean"],
            "narrativeSignals": ["confidence", "precision", "understated elegance", "curation"],
            "plannerInterpretation": "Every element earns its place. The absence of excess is the statement."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "garden-romance",
        "name": "Garden Romance",
        "site_type": "garden",
        "short_description": "Lush outdoor garden with pastel blooms, soft lighting, and timeless romance.",
        "profile_json": {
            "styleTags": ["garden", "floral", "pastel", "romantic", "outdoor"],
            "personaSignals": ["romantic couple", "nature lovers", "flower enthusiasts", "classic tastes"],
            "vibeTags": ["romantic", "soft", "timeless", "joyful"],
            "culturalSignals": ["pan-Indian", "English garden influence", "spring festival"],
            "seasonTags": ["spring", "early summer", "winter"],
            "settingTags": ["botanical garden", "lawn", "farmhouse garden", "resort garden"],
            "audienceFit": ["romantic & intimate vibe", "floral lovers", "outdoor wedding seekers"],
            "luxuryLevel": "medium",
            "colorSignals": ["blush", "lavender", "soft yellow", "white", "peach"],
            "spatialMood": ["open", "bloom-filled", "soft-lit", "airy paths"],
            "narrativeSignals": ["romance", "new beginnings", "joy", "nature"],
            "plannerInterpretation": "The garden is the palette. Florals extend rather than replace the natural setting."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "sufi-night",
        "name": "Sufi Night",
        "site_type": "mystical",
        "short_description": "Mystical and soulful. Lanterns, qawwali, warm amber light, and spiritual depth.",
        "profile_json": {
            "styleTags": ["mystical", "sufi", "lantern-lit", "amber", "soulful"],
            "personaSignals": ["music lovers", "spiritually inclined", "culturally deep", "experience-first couple"],
            "vibeTags": ["soulful", "warm", "mystical", "immersive"],
            "culturalSignals": ["Sufi tradition", "Mughal influence", "North India", "qawwali culture"],
            "seasonTags": ["winter", "late autumn"],
            "settingTags": ["dargah courtyard", "heritage garden", "enclosed lawn", "fort courtyard"],
            "audienceFit": ["whimsical vibe", "music-focused couples", "experience-seekers"],
            "luxuryLevel": "medium",
            "colorSignals": ["amber", "deep orange", "cream", "copper", "indigo"],
            "spatialMood": ["lantern-hung", "low-lit", "immersive", "candlelight-heavy"],
            "narrativeSignals": ["soul", "devotion", "community", "music"],
            "plannerInterpretation": "Music and light are the primary design elements. Architecture supports rather than leads."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "mountain-retreat",
        "name": "Mountain Retreat",
        "site_type": "mountain",
        "short_description": "Himalayan setting with cozy intimacy, pine-scented air, and understated mountain luxury.",
        "profile_json": {
            "styleTags": ["mountain", "Himalayan", "cozy", "intimate", "nature-first"],
            "personaSignals": ["adventure couple", "mountain lovers", "introvert-leaning", "experience-first"],
            "vibeTags": ["intimate", "adventurous", "cozy", "serene"],
            "culturalSignals": ["Himachal", "Uttarakhand", "destination India"],
            "seasonTags": ["spring", "summer", "early autumn"],
            "settingTags": ["mountain resort", "forest clearing", "riverside", "hilltop property"],
            "audienceFit": ["intimate vibe", "destination couples", "nature lovers"],
            "luxuryLevel": "medium",
            "colorSignals": ["pine green", "stone grey", "warm cream", "bark brown", "copper"],
            "spatialMood": ["panoramic views", "fire-lit", "natural materials", "organic"],
            "narrativeSignals": ["escape", "connection", "nature", "quiet celebration"],
            "plannerInterpretation": "The mountains frame everything. Design keeps out of nature's way."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "golden-hour-farm",
        "name": "Golden Hour Farm",
        "site_type": "rustic",
        "short_description": "Farmhouse wedding bathed in golden hour light. Rustic warmth, open skies, and harvest textures.",
        "profile_json": {
            "styleTags": ["farmhouse", "rustic", "golden", "organic", "harvest"],
            "personaSignals": ["relaxed couple", "outdoor lovers", "foodies", "non-traditional"],
            "vibeTags": ["warm", "relaxed", "earthy", "joyful"],
            "culturalSignals": ["pan-Indian", "eco-weddings", "farm-to-table culture"],
            "seasonTags": ["winter", "late autumn", "early spring"],
            "settingTags": ["farmhouse", "open field", "orchard", "agricultural estate"],
            "audienceFit": ["relaxed & easy vibe", "foodie couples", "outdoor crowd"],
            "luxuryLevel": "medium-low",
            "colorSignals": ["golden yellow", "burnt sienna", "cream", "olive", "wood"],
            "spatialMood": ["open sky", "golden-lit", "hay-textured", "string lights"],
            "narrativeSignals": ["abundance", "harvest", "warmth", "togetherness"],
            "plannerInterpretation": "The light at golden hour does more than any decorator. Timing is the primary design decision."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "art-deco-palace",
        "name": "Art Deco Palace",
        "site_type": "editorial",
        "short_description": "1920s glamour in an Indian palace setting. Bold geometry, champagne gold, and theatrical drama.",
        "profile_json": {
            "styleTags": ["Art Deco", "glamour", "geometric", "editorial", "opulent"],
            "personaSignals": ["design-obsessed couple", "fashion-forward", "bold choices", "dramatic flair"],
            "vibeTags": ["dramatic", "glamorous", "bold", "theatrical"],
            "culturalSignals": ["colonial India", "1920s-30s aesthetic", "Bombay heritage"],
            "seasonTags": ["winter", "any season"],
            "settingTags": ["palace hotel", "art deco building", "heritage hotel", "grand ballroom"],
            "audienceFit": ["dramatic & theatrical vibe", "fashion-conscious couples"],
            "luxuryLevel": "high",
            "colorSignals": ["champagne", "black", "deep teal", "gold", "ivory"],
            "spatialMood": ["geometric patterns", "high ceilings", "mirror accents", "chandeliers"],
            "narrativeSignals": ["glamour", "drama", "sophistication", "old world elegance"],
            "plannerInterpretation": "Architecture sets the decade. Direction focuses on costume, staging, and choreography of arrivals."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "rooftop-sundowner",
        "name": "Rooftop Sundowner",
        "site_type": "cocktail",
        "short_description": "Sunset cocktail celebration on a city rooftop. Social, high-energy, and effortlessly cool.",
        "profile_json": {
            "styleTags": ["rooftop", "sundowner", "cocktail", "social", "contemporary"],
            "personaSignals": ["social couple", "friend-circle led", "party-first", "urban millennials"],
            "vibeTags": ["festive", "social", "high-energy", "modern"],
            "culturalSignals": ["metro India", "Mumbai", "Delhi", "Bangalore nightlife culture"],
            "seasonTags": ["winter", "late autumn"],
            "settingTags": ["rooftop bar", "terrace", "penthouse", "sky venue"],
            "audienceFit": ["big & festive vibe", "social crowd", "friend-first weddings"],
            "luxuryLevel": "medium-high",
            "colorSignals": ["burnt orange", "gold", "sunset pink", "terracotta", "warm white"],
            "spatialMood": ["open sky", "sunset-lit", "bar-forward", "music-filled"],
            "narrativeSignals": ["celebration", "friendship", "city nights", "joy"],
            "plannerInterpretation": "The sunset is the hero. Design is secondary to atmosphere, music, and timing."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
    {
        "slug": "south-indian-classical",
        "name": "Festive Carnatic",
        "site_type": "classical",
        "short_description": "Vibrant South Indian classical wedding. Silk, jasmine, brass lamps, and deep cultural texture.",
        "profile_json": {
            "styleTags": ["South Indian", "classical", "traditional", "vibrant", "cultural"],
            "personaSignals": ["culturally rooted couple", "traditional family", "ritual-first", "heritage-proud"],
            "vibeTags": ["traditional", "vibrant", "warm", "family-led"],
            "culturalSignals": ["Tamil", "Telugu", "Kannada", "Kerala", "Brahmin traditions", "Carnatic music"],
            "seasonTags": ["any season"],
            "settingTags": ["temple hall", "convention center", "traditional mandap", "family home"],
            "audienceFit": ["traditional & rooted vibe", "family-led couples", "South Indian households"],
            "luxuryLevel": "medium",
            "colorSignals": ["kanjivaram red", "gold zari", "yellow", "green", "banana leaf"],
            "spatialMood": ["jasmine-scented", "brass-lamp lit", "silk-draped", "ritual-centered"],
            "narrativeSignals": ["tradition", "family", "ritual", "blessing"],
            "plannerInterpretation": "The rituals are the design. Planning focuses on flow, timing, and sensory richness rather than visual overdesign."
        },
        "hero_image_url": None,
        "gallery_json": [],
        "is_active": True,
        "seed_version": "v1",
    },
]
