"""happinest_schema_v1

Revision ID: ba7e52c55a34
Revises: 
Create Date: 2026-07-10 05:48:54.065674+00:00

"""
from typing import Sequence, Union

import pgvector.sqlalchemy  # noqa: F401 — required for vector column type
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba7e52c55a34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('site_type', sa.String(length=50), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('gallery_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sites_site_type'), 'event_sites', ['site_type'], unique=False)
    op.create_index(op.f('ix_event_sites_slug'), 'event_sites', ['slug'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('memory_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('partner_name', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('occasion_type', sa.String(length=50), nullable=False),
    sa.Column('last_provider_response_id', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vendor_type', sa.String(length=50), nullable=False),
    sa.Column('primary_city', sa.String(length=100), nullable=False),
    sa.Column('primary_region', sa.String(length=100), nullable=False),
    sa.Column('short_description', sa.Text(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rating_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('seed_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_primary_city'), 'vendors', ['primary_city'], unique=False)
    op.create_index(op.f('ix_vendors_slug'), 'vendors', ['slug'], unique=True)
    op.create_index(op.f('ix_vendors_vendor_type'), 'vendors', ['vendor_type'], unique=False)
    op.create_table('ai_turn_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_family', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('response_source', sa.String(length=20), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('provider_response_id', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_turn_logs_request_id'), 'ai_turn_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ai_turn_logs_session_id'), 'ai_turn_logs', ['session_id'], unique=False)
    op.create_table('generated_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_from_memory_version', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_artifacts_session_id'), 'generated_artifacts', ['session_id'], unique=False)
    op.create_table('session_event_site_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_site_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_batch_id', sa.UUID(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_from_memory_version', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_site_id'], ['event_sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_event_site_recommendations_recommendation_batch_id'), 'session_event_site_recommendations', ['recommendation_batch_id'], unique=False)
    op.create_index(op.f('ix_session_event_site_recommendations_session_id'), 'session_event_site_recommendations', ['session_id'], unique=False)
    op.create_table('session_memory_patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('from_version_no', sa.Integer(), nullable=True),
    sa.Column('to_version_no', sa.Integer(), nullable=False),
    sa.Column('patch_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_memory_patches_session_id'), 'session_memory_patches', ['session_id'], unique=False)
    op.create_table('session_memory_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('memory_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stale_sections', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('open_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by_request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'version_no', name='uq_session_memory_version')
    )
    op.create_index(op.f('ix_session_memory_versions_session_id'), 'session_memory_versions', ['session_id'], unique=False)
    op.create_table('session_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_messages_session_id'), 'session_messages', ['session_id'], unique=False)
    op.create_table('session_stage_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=50), nullable=True),
    sa.Column('to_stage', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_stage_history_session_id'), 'session_stage_history', ['session_id'], unique=False)
    op.create_table('session_vendor_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_batch_id', sa.UUID(), nullable=False),
    sa.Column('rank_order', sa.Integer(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('generated_from_memory_version', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_vendor_recommendations_recommendation_batch_id'), 'session_vendor_recommendations', ['recommendation_batch_id'], unique=False)
    op.create_index(op.f('ix_session_vendor_recommendations_session_id'), 'session_vendor_recommendations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_vendor_recommendations_session_id'), table_name='session_vendor_recommendations')
    op.drop_index(op.f('ix_session_vendor_recommendations_recommendation_batch_id'), table_name='session_vendor_recommendations')
    op.drop_table('session_vendor_recommendations')
    op.drop_index(op.f('ix_session_stage_history_session_id'), table_name='session_stage_history')
    op.drop_table('session_stage_history')
    op.drop_index(op.f('ix_session_messages_session_id'), table_name='session_messages')
    op.drop_table('session_messages')
    op.drop_index(op.f('ix_session_memory_versions_session_id'), table_name='session_memory_versions')
    op.drop_table('session_memory_versions')
    op.drop_index(op.f('ix_session_memory_patches_session_id'), table_name='session_memory_patches')
    op.drop_table('session_memory_patches')
    op.drop_index(op.f('ix_session_event_site_recommendations_session_id'), table_name='session_event_site_recommendations')
    op.drop_index(op.f('ix_session_event_site_recommendations_recommendation_batch_id'), table_name='session_event_site_recommendations')
    op.drop_table('session_event_site_recommendations')
    op.drop_index(op.f('ix_generated_artifacts_session_id'), table_name='generated_artifacts')
    op.drop_table('generated_artifacts')
    op.drop_index(op.f('ix_ai_turn_logs_session_id'), table_name='ai_turn_logs')
    op.drop_index(op.f('ix_ai_turn_logs_request_id'), table_name='ai_turn_logs')
    op.drop_table('ai_turn_logs')
    op.drop_index(op.f('ix_vendors_vendor_type'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_slug'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_primary_city'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_event_sites_slug'), table_name='event_sites')
    op.drop_index(op.f('ix_event_sites_site_type'), table_name='event_sites')
    op.drop_table('event_sites')
    # ### end Alembic commands ###
